<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-FEOO1RA" failures="1" tests="8" name="testCases.TC_001_Registration" time="41.517" errors="0" timestamp="2024-09-28T16:57:07 IST" skipped="0">
  <testcase classname="testCases.TC_001_Registration" name="sanity" time="0.050"/>
  <system-out/>
  <testcase classname="testCases.TC_001_Registration" name="verifyNavigateRegPage" time="8.388"/>
  <system-out/>
  <testcase classname="testCases.TC_001_Registration" name="reg" time="0.008"/>
  <system-out/>
  <testcase classname="testCases.TC_001_Registration" name="reg" time="0.108"/>
  <system-out/>
  <testcase classname="testCases.TC_001_Registration" name="verifyNavigateRegPage" time="8.231"/>
  <system-out/>
  <testcase classname="testCases.TC_001_Registration" name="sanity" time="0.010">
    <failure message="expected [chrome] but found [edge]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [chrome] but found [edge]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at testCases.TC_001_Registration.sanity(TC_001_Registration.java:68)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:136)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:658)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:219)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:923)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:192)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:32)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:467)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- sanity -->
  <system-out/>
  <testcase classname="testCases.TC_001_Registration" name="verifyAccountReg" time="11.423"/>
  <system-out/>
  <testcase classname="testCases.TC_001_Registration" name="verifyAccountReg" time="13.299"/>
  <system-out/>
</testsuite> <!-- testCases.TC_001_Registration -->
